apiVersion: apps/v1
kind: Deployment
metadata:
  name: dresp-deployment
  labels:
    app: dresp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dresp

  template:
    metadata:
      labels:
        app: dresp
    spec:
      containers:
        - name: dresp-web
          image: ghcr.io/ktmrmshk/dresp:latest
---
apiVersion: v1
kind: Service
metadata:
  name: dresp-service
spec:
  type: NodePort
  selector:
    app: dresp
  ports:
    - port: 5000
      nodePort: 30005
